import "./globals.css";
export const metadata = {
  title: "Sun Power",
  description: "Generated by create next app",
  icons: { image: "/image/1000106246-removebg-preview.png" },
};
export default function RootLayout({ children }) {
  return <>{children}</>;
}
